# Generated by Django 3.1.7 on 2021-03-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store', 'product_name')},
        ),
    ]
