# Generated by Django 3.1.7 on 2021-03-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210321_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('type', models.TextField(max_length=90, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
    ]
