# Generated by Django 3.1.7 on 2021-03-21 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default='misc', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='store.category'),
        ),
    ]
