# Generated by Django 3.1.7 on 2021-03-22 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='seller_user',
        ),
    ]
