# Generated by Django 3.1.7 on 2021-03-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20210322_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Declined', 'Declined')], default='Submitted', max_length=20),
        ),
    ]
