# Generated by Django 3.1.7 on 2021-03-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
